name: Update package version
run-name: ${{ github.actor }} is updating the package version 🚀
on: [push]
jobs:
  Update-Package-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python Script
        run: |
          python modify_git_tag.py
      - name: Commit changes
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated update"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
     
      # - name: Commit and push changes
      #   uses: actions/checkout@v3
      #   run: |
      #     if git diff --quiet && git diff --cached --quiet; then 
      #       echo "No changes to commit or push." 
      #     else 
      #       git commit -m "package.json automatic update by GitHub Action" && git push 
      #     fi
        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
        #   commit_message: "package.json automatic update by GitHub Action"
        #   commit_user_name: "GitHub Actions"
        #   commit_user_email: "actions@github.com"
      - run: echo "🍏 This job's status is ${{ job.status }}."