name: Update package version
run-name: ${{ github.actor }} is updating the package version 🚀
on:
  push:
    tags:
      - 'v*'
jobs:
  Update-Package-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python Script
        run: |
          python modify_git_tag.py
          git status
          git diff-index HEAD
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if [ -n "$(git status --porcelain)" ]
          then
            touch BRANCH_NAME
            touch CACHED_TAG
            git branch --contains ${{ github.ref }} > BRANCH_NAME
            git describe --tags --abbrev=0 > CACHED_TAG
            git commit -m "Automated tag update"
            git tag -f $(cat CACHED_TAG)
            git checkout $(cat BRANCH_NAME)
            git push
            rm CACHED_TAG
            rm BRANCH_NAME
            echo "Changes commited and pushed"
          else
            echo "No changes found"
          fi
      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
      #     tags: true
      - run: echo "🍏 This job's status is ${{ job.status }}."