name: Update package version
run-name: ${{ github.actor }} is updating the package version 🚀
on:
  push:
    tags:
      - 'v*'
jobs:
  Update-Package-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python Script
        run: |
          python modify_git_tag.py
          git status
          git diff-index HEAD
      - name: Get branch name for tag
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          branch_name=$(git branch --contains $tag_name | grep -v detached | cut -c3-)
          touch BRANCH_NAME
          touch TAG_NAME
          echo "$branch_name" > BRANCH_NAME
          echo "Content of BRANCH_NAME file:"
          cat BRANCH_NAME
          echo "$tag_name" > CACHED_TAG
          echo "Content of CACHED_TAG file:"
          cat CACHED_TAG
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if [ -n "$(git status --porcelain)" ]
          then
            git checkout $(cat BRANCH_NAME)
            git commit -m "Automated tag update"
            git tag -f $(cat CACHED_TAG)
            git push
            rm CACHED_TAG
            rm BRANCH_NAME
            echo "Changes commited and pushed"
          else
            echo "No changes found"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."