name: Update package version
run-name: ${{ github.actor }} is updating the package version 🚀
on:
  push:
    tags:
      - 'v*'
jobs:
  Update-Package-Version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python Script
        run: |
          python modify_git_tag.py
          git status
          git diff-index HEAD
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if [ -n "$(git status --porcelain)" ]
          then
            git checkout -b ${GITHUB_REF#refs/tags/}_tag_update_branch
            git commit -m "Automated tag update for ${GITHUB_REF#refs/tags/}"
            git push --set-upstream origin ${GITHUB_REF#refs/tags/}_tag_update_branch
            git push --delete origin ${GITHUB_REF#refs/tags/}
            git tag -a ${GITHUB_REF#refs/tags/} -m "Tag message for ${GITHUB_REF#refs/tags/}" HEAD
            git push origin ${GITHUB_REF#refs/tags/}
            echo "Changes commited and pushed"
          else
            echo "No changes found"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."