name: Update package version
run-name: ${{ github.actor }} is updating the package version 🚀
on:
  push:
    tags:
      - 'v*'
jobs:
  Update-Package-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Python Script
        run: |
          python modify_git_tag.py
          git status
          git diff-index HEAD
      - name: Get tag name
        run: |
          tag_name=${GITHUB_REF#refs/tags/}
          touch TAG_NAME
          echo "$tag_name" > CACHED_TAG
          echo "Content of CACHED_TAG file:"
          cat CACHED_TAG
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if [ -n "$(git status --porcelain)" ]
          then
            git checkout -b $(cat CACHED_TAG)_tag_update_branch
            git commit -m "Automated tag update for $(cat CACHED_TAG)"
            git tag -f $(cat CACHED_TAG)
            git push --set-upstream origin $(cat CACHED_TAG)_tag_update_branch
            rm CACHED_TAG
            echo "Changes commited and pushed"
          else
            echo "No changes found"
          fi
      - run: echo "🍏 This job's status is ${{ job.status }}."